name: generate docker build script
description: generates docker build script

inputs:
  Tag:
    description: tag string for docker build
  ParamsEnv:
    required: true
    description: string of aws parameters like in a .env file format
  DockerfileName:
    required: true
    description: json string of task definition
  ScriptFileName:
    required: false
    default: ""
    description: json string of task definition

runs:
  using: node16
  main: dist/index.js
